const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const resource = b.dependency("lenore_resources", .{ .target = target, .optimize = optimize });
    const zmath = b.dependency("zmath", .{}).module("root");

    const mod = b.addModule("lenore-scene", .{
        .root_source_file = b.path("src/root.zig"),
        .imports = &.{
            .{ .name = "lenore-resources", .module = resource.module("lenore-resources") },
            .{ .name = "zmath", .module = zmath },
        },
        .target = target,
        .optimize = optimize,
    });

    const unit_tests = b.addTest(.{
        .root_module = b.createModule(.{
            .root_source_file = testRoot(b, "tests"),
            .imports = &.{
                .{ .name = "lenore-scene", .module = mod },
                .{ .name = "lenore-resources", .module = resource.module("lenore-resources") },
                .{ .name = "zmath", .module = zmath },
            },
            .target = target,
            .optimize = optimize,
        }),
    });
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&b.addRunArtifact(unit_tests).step);

    const module_tests = b.addTest(.{ .root_module = mod });
    test_step.dependOn(&b.addRunArtifact(module_tests).step);

    const examples_step = b.step("examples", "Build every example");
    b.getInstallStep().dependOn(examples_step);
    for (zigFilesIn(b, "examples")) |name| {
        const stem = name[0 .. name.len - ".zig".len];
        const exe = b.addExecutable(.{
            .name = stem,
            .root_module = b.createModule(.{
                .root_source_file = b.path(b.fmt("examples/{s}", .{name})),
                .imports = &.{
                    .{ .name = "lenore-scene", .module = mod },
                    .{ .name = "lenore-resources", .module = resource.module("lenore-resources") },
                    .{ .name = "zmath", .module = zmath },
                },
                .target = target,
                .optimize = optimize,
            }),
        });
        examples_step.dependOn(&b.addInstallArtifact(exe, .{}).step);

        const run = b.addRunArtifact(exe);
        if (b.args) |args| run.addArgs(args);
        b.step(b.fmt("run-{s}", .{stem}), b.fmt("Run the {s} example", .{stem}))
            .dependOn(&run.step);
    }
}

fn zigFilesIn(b: *std.Build, dir_path: []const u8) [][]const u8 {
    var names: std.ArrayList([]const u8) = .empty;
    const io = b.graph.io;
    var dir = b.build_root.handle.openDir(io, dir_path, .{ .iterate = true }) catch |err| switch (err) {
        error.FileNotFound => return names.items,
        else => std.debug.panic("cannot open {s}/: {t}", .{ dir_path, err }),
    };
    defer dir.close(io);

    var iterator = dir.iterate();
    while (iterator.next(io) catch @panic("cannot list the directory")) |entry| {
        if (entry.kind != .file or !std.mem.endsWith(u8, entry.name, ".zig")) continue;
        names.append(b.allocator, b.dupe(entry.name)) catch @panic("OOM");
    }

    std.mem.sort([]const u8, names.items, {}, struct {
        fn lessThan(_: void, a: []const u8, b_: []const u8) bool {
            return std.mem.order(u8, a, b_) == .lt;
        }
    }.lessThan);
    return names.items;
}

fn testRoot(b: *std.Build, dir_path: []const u8) std.Build.LazyPath {
    var source: std.ArrayList(u8) = .empty;
    source.appendSlice(b.allocator, "// Generated by build.zig from the test directory. Do not edit.\ntest {\n") catch @panic("OOM");
    for (zigFilesIn(b, dir_path)) |name|
        source.print(b.allocator, "    _ = @import(\"{s}/{s}\");\n", .{ dir_path, name }) catch @panic("OOM");
    source.appendSlice(b.allocator, "}\n") catch @panic("OOM");

    const generated = b.addWriteFiles();
    _ = generated.addCopyDirectory(b.path(dir_path), dir_path, .{});
    return generated.add("test_root.zig", source.items);
}
